name: Update Xeno DLL

on:
  schedule:
    - cron: "0 */6 * * *" # prüft alle 6 Stunden/checks every 6hrs
  workflow_dispatch: # manuell startbar

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Download ZIP
      run: wget -O xeno.zip https://xeno.onl/downloads/Xeno-v1.3.05.zip

    - name: Extract ZIP
      run: unzip -o xeno.zip -d xeno

    - name: Move Xeno.dll
      run: |
        mkdir -p dll
        if [ -f xeno/Xeno.dll ]; then
          cp xeno/Xeno.dll dll/Xeno.dll
        else
          find xeno -name "Xeno.dll" -exec cp {} dll/Xeno.dll \;
        fi

    - name: Commit changes if updated
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add dll/Xeno.dll
        if ! git diff --staged --quiet; then
          git commit -m "Auto update Xeno.dll"
          git push
        else
          echo "Keine Änderungen"
        fi
